name: Code Format

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  format:
    name: Code Format
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Code Format
        run: npm run format:check:all