name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-generator:
    name: Test
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3 

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
        # Must change shell as you are using the windows-latest image 
      - name: Set npm shell
        run: npm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe"
      
      - name: Install Node.js dependencies globally
        run: |
          npm install

      - name: Install Forge
        run: |
          cd ..
          git clone https://github.com/ScottLogic/openapi-forge.git
          cd openapi-forge
          npm install
          npm install -g

      - name: test-generator
        run: npm run test
        continue-on-error: true